language: bash
sudo: true
services:
  - docker

before_install:
  - docker info
  - docker version
  
  - echo "==> Build with Docker ..."
  
  # Ubuntu
  - docker build -f tests/Dockerfile.ubuntu12.04  -t vim:ubuntu12.04 . | tee tests/output.ubuntu12.04.log
  - docker build -f tests/Dockerfile.ubuntu14.04  -t vim:ubuntu14.04 . | tee tests/output.ubuntu14.04.log
  - docker build -f tests/Dockerfile.ubuntu16.04  -t vim:ubuntu16.04 . | tee tests/output.ubuntu16.04.log
  
  # Debian
  - docker build -f tests/Dockerfile.debian7 -t vim:debian7 .    | tee tests/output.debian7.log
  - docker build -f tests/Dockerfile.debian8 -t vim:debian8 .    | tee tests/output.debian8.log
  
  # CentOS
  - docker build -f tests/Dockerfile.centos6 -t vim:centos6 .    | tee tests/output.centos6.log
  - docker build -f tests/Dockerfile.centos7 -t vim:centos7 .    | tee tests/output.centos7.log
  
script:
  - echo "==> Run Test case ..."
  
  # Ubuntu
  - grep 'VIM - Vi IMproved' tests/output.ubuntu12.04.log
  - grep 'VIM - Vi IMproved' tests/output.ubuntu14.04.log
  - grep 'VIM - Vi IMproved' tests/output.ubuntu16.04.log

  # Debian
  - grep 'VIM - Vi IMproved' tests/output.debian7.log
  - grep 'VIM - Vi IMproved' tests/output.debian8.log

  # CentOS
  - grep 'VIM - Vi IMproved' tests/output.centos6.log
  - grep 'VIM - Vi IMproved' tests/output.centos7.log

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  hipchat:
    secure: "DTnXg490xbC3HB3Qs/8aSDSRlrVUBWrDzywuo6+PJrTrQFZbAbn1Xeey9wmibkIB6AigZew+EeBTcmIkactb6zH8cTwOBAaZIAiU2SgMjCBkMXOPblvCd9DToL8ul5/jkwu8ZfV91ncrujczajZDPA1qaKhU3LKqpCVCHIxptRyX2FRsiGS1/2IJSWM/GdVWHzRr4OdYcLixqPlC40iQf6sDlCJAlGmkNSGyMDJ9nOlPKH0fRXW+DBSUMcbYFYO7v3AfDlBibWcaCohhVfaMeYt0BGuQ0cDaxMPPqJbvBySHB04OGFbjFCnQgQe9Q/e7SlUctoKumzloIwcoJOnKtZpHuayXYegRSbUuvVhm0E2a3OHjeuenKdjddF1lOAuUyBal3Jlqy1yIwLafW6lCNaR2+xyJ/tcL2Ds/SSTFnvzxZH1j43acJ59mkFjrA6TQUt81sOG4nlFjHOoD+DriCY1tc6WVP3IltjZUyQBvOrg08DtnTHCJYMG6Yep9hg9y4WO7Hi/3eWiA4z8vYNzOBOz2xVKlqyWTTELwSp04PsnZHxmRInoXdPYK0Jmyh3qNtslcw4l5oHb0htFwyqCPBWbjb0wm/5OrIVcnFXYt9k3/uDOCzz9QsPhulg5Ei+159gNMn4w9djzLVK4IUkzBf/X4PwwH7h56WccHsCGchsc="

