language: bash
sudo: true
services:
  - docker

before_install:
  - docker info
  - docker version
  - echo "==> Build with Docker ..."
  - docker build -f tests/Dockerfile.ubuntu12.04 -t vim:ubuntu12.04 . | tee tests/output.ubuntu12.04.log
  - docker build -f tests/Dockerfile.ubuntu14.04 -t vim:ubuntu14.04 . | tee tests/output.ubuntu14.04.log
  - docker build -f tests/Dockerfile.ubuntu16.04 -t vim:ubuntu16.04 . | tee tests/output.ubuntu16.04.log
  - docker build -f tests/Dockerfile.debian7 -t vim:debian7 . | tee tests/output.debian7.log
  - docker build -f tests/Dockerfile.debian8 -t vim:debian8 . | tee tests/output.debian8.log
  - docker build -f tests/Dockerfile.debian9 -t vim:debian9 . | tee tests/output.debian9.log
  - docker build -f tests/Dockerfile.centos6 -t vim:centos6 . | tee tests/output.centos6.log
  - docker build -f tests/Dockerfile.centos7 -t vim:centos7 . | tee tests/output.centos7.log

script:
  - echo "==> Run Test case ..."
  - grep 'VIM - Vi IMproved' tests/output.ubuntu12.04.log
  - grep 'VIM - Vi IMproved' tests/output.ubuntu14.04.log
  - grep 'VIM - Vi IMproved' tests/output.ubuntu16.04.log
  - grep 'VIM - Vi IMproved' tests/output.debian7.log
  - grep 'VIM - Vi IMproved' tests/output.debian8.log
  - grep 'VIM - Vi IMproved' tests/output.debian9.log
  - grep 'VIM - Vi IMproved' tests/output.centos6.log
  - grep 'VIM - Vi IMproved' tests/output.centos7.log

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: H7bSfCL234KFovfWn1RGr4szDDFE1/tVJhj1FTXwSCdI75opuXYd2mGZX65jVeeSdCNuN03EooLLWPoYc6FXZKKVr60QehoDHaa8tcHDfk0paumx1ptkL8xcocP3hIRZMns58i3kD/jjFpbTQJs7VkeE5yMZ+Qokjp83Oq2tuxSSO5TLTfwj/WujLBQxJziL49Sjc+Cn7AmCANVjTeR38d/DW5WD7qp7Echd8pll7bqAWaqSOGEDLyi5mNQmtRn+US2yAQXkvkL3/7CoM0ksfHPjoZPfGGpS74cErKaZNgvAdj99BIcjnUrbBIO7A2lqXzgTeIRmttZ8Xh8vdQVT/IXnOQ4u/ZpMhbdQatUz5OF6hhayeLg7JBo5wAZkLywW1WGjBD2ohA5rDc2mN5G/gwvOUh7jmyZrcc3RiYl1RS8BrAes/4LyHDxIIVzuIBs9VLxnzWmW8UH2VpVTxIDcD2pubsOhYtGvZYlDzid3/59aCRe9HQPLfMHdJGW17a2mofj06b99gXWhieBkeUK9jY7m46t7s9hRpDB3oqvJVC5+dNRN7wkKWMPfOxT/2ohhQhAh0syW+67kUCRlmVmYGIrpgwusYL/AaGQmsw+GjgDrdifeeqSp6H19gX4t+bvbagdl2CNOVjT9IWsDLlK1wcV/uR/IjQmp0jEZSHYxasM=
