language: bash
sudo: true
services:
  - docker

before_install:
  - docker info
  - docker version
  
  - echo "==> Build with Docker ..."
  
  # Ubuntu
  - docker build -f test/Dockerfile.ubuntu12  -t vim:ubuntu12 . | tee build_result.ubuntu12
  - docker build -f test/Dockerfile.ubuntu14  -t vim:ubuntu14 . | tee build_result.ubuntu14
  #- docker build -f test/Dockerfile.ubuntu16  -t vim:ubuntu16 . | tee build_result.ubuntu16
  
  # Debian
  - docker build -f test/Dockerfile.debian7 -t vim:debian7 .    | tee build_result.debian7
  - docker build -f test/Dockerfile.debian8 -t vim:debian8 .    | tee build_result.debian8
  
  # CentOS
  #- docker build -f test/Dockerfile.centos6 -t vim:centos6 .    | tee build_result.centos6
  #- docker build -f test/Dockerfile.centos7 -t vim:centos7 .    | tee build_result.centos7
  
script:
  - echo "==> Run Test case ..."
  
  - grep 'VIM - Vi IMproved' build_result.ubuntu12
  - grep 'VIM - Vi IMproved' build_result.ubuntu14
  #- grep 'VIM - Vi IMproved' build_result.ubuntu16

  - grep 'VIM - Vi IMproved' build_result.debian7
  - grep 'VIM - Vi IMproved' build_result.debian8

  #- grep 'VIM - Vi IMproved' build_result.centos6
  #- grep 'VIM - Vi IMproved' build_result.centos7

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

