language: bash
sudo: required
services:
  - docker

before_install:
  - docker info
  - docker version

jobs:
  include:

    # Stage of Syntax check
    # =====================

    - stage: Syntax check
      script:
        - echo "==> Syntax Check on Ansible 2.4 ..."
        - docker run --rm -it -v $PWD:/srv chusiang/ansible:2.4 /bin/sh -c "cd /srv && ansible-playbook --syntax-check provision.yml"

    - stage: Syntax check
      script:
        - echo "==> Syntax Check on Ansible 2.5 ..."
        - docker run --rm -it -v $PWD:/srv chusiang/ansible:2.5 /bin/sh -c "cd /srv && ansible-playbook --syntax-check provision.yml"

    # Stage of Lint check
    # ===================

    - stage: Lint check
      script:
        - echo "==> Lint Check on Ansible 2.4 ..."
        - docker run --rm -it -v $PWD:/srv chusiang/ansible:2.4 /bin/sh -c "cd /srv && ansible-lint provision.yml"

    - stage: Lint check
      script:
        - echo "==> Lint Check on Ansible 2.5 ..."
        - docker run --rm -it -v $PWD:/srv chusiang/ansible:2.5 /bin/sh -c "cd /srv && ansible-lint provision.yml"

    # Stage of Build
    # ==============

    - stage: Build
      script:
        - echo "==> Build on Alpine 3 ..."
        - docker build -f tests/Dockerfile.alpine3 -t vim:alpine3 . | tee tests/output.alpine3.log

        - echo "==> Run test case on Alpine 3 ..."
        - grep 'VIM - Vi IMproved' tests/output.alpine3.log

    - stage: Build
      script:
        - echo "==> Build on CentOS 7 ..."
        - docker build -f tests/Dockerfile.centos7 -t vim:centos7 . | tee tests/output.centos7.log

        - echo "==> Run test case on CentOS 7 ..."
        - grep 'VIM - Vi IMproved' tests/output.centos7.log

    - stage: Build
      script:
        - echo "==> Build on Debian 8 ..."
        - docker build -f tests/Dockerfile.debian8 -t vim:debian8 . | tee tests/output.debian8.log

        - echo "==> Run test case on Debian 8 ..."
        - grep 'VIM - Vi IMproved' tests/output.debian8.log

    - stage: Build
      script:
        - echo "==> Build on Debian 9 ..."
        - docker build -f tests/Dockerfile.debian9 -t vim:debian9 . | tee tests/output.debian9.log

        - echo "==> Run test case on Debian 9 ..."
        - grep 'VIM - Vi IMproved' tests/output.debian9.log

    - stage: Build
      script:
        - echo "==> Build on Ubuntu 14.04 ..."
        - docker build -f tests/Dockerfile.ubuntu14.04 -t vim:ubuntu14.04 . | tee tests/output.ubuntu14.04.log

        - echo "==> Run test case on Ubuntu 14.04 ..."
        - grep 'VIM - Vi IMproved' tests/output.ubuntu14.04.log

    - stage: Build
      script:
        - echo "==> Build on Ubuntu 16.04 ..."
        - docker build -f tests/Dockerfile.ubuntu16.04 -t vim:ubuntu16.04 . | tee tests/output.ubuntu16.04.log

        - echo "==> Run test case on Ubuntu 16.04 ..."
        - grep 'VIM - Vi IMproved' tests/output.ubuntu16.04.log

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: H7bSfCL234KFovfWn1RGr4szDDFE1/tVJhj1FTXwSCdI75opuXYd2mGZX65jVeeSdCNuN03EooLLWPoYc6FXZKKVr60QehoDHaa8tcHDfk0paumx1ptkL8xcocP3hIRZMns58i3kD/jjFpbTQJs7VkeE5yMZ+Qokjp83Oq2tuxSSO5TLTfwj/WujLBQxJziL49Sjc+Cn7AmCANVjTeR38d/DW5WD7qp7Echd8pll7bqAWaqSOGEDLyi5mNQmtRn+US2yAQXkvkL3/7CoM0ksfHPjoZPfGGpS74cErKaZNgvAdj99BIcjnUrbBIO7A2lqXzgTeIRmttZ8Xh8vdQVT/IXnOQ4u/ZpMhbdQatUz5OF6hhayeLg7JBo5wAZkLywW1WGjBD2ohA5rDc2mN5G/gwvOUh7jmyZrcc3RiYl1RS8BrAes/4LyHDxIIVzuIBs9VLxnzWmW8UH2VpVTxIDcD2pubsOhYtGvZYlDzid3/59aCRe9HQPLfMHdJGW17a2mofj06b99gXWhieBkeUK9jY7m46t7s9hRpDB3oqvJVC5+dNRN7wkKWMPfOxT/2ohhQhAh0syW+67kUCRlmVmYGIrpgwusYL/AaGQmsw+GjgDrdifeeqSp6H19gX4t+bvbagdl2CNOVjT9IWsDLlK1wcV/uR/IjQmp0jEZSHYxasM=
