#!/usr/bin/env ansible-playbook
---

- name: provision the vim and vi mode
  hosts: all
  vars_files:
    - defaults/main.yml

  tasks:
    - name: include main tasks
      import_tasks: tasks/main.yml

    - name: check vim version
      command: vim --version
      register: vim_version
      changed_when: False

    - name: print vim version
      debug:
        msg: "{{ vim_version.stdout_lines }}"

# vim: ft=ansible :
