#!/usr/bin/env ansible-playbook
---

- name: delegate to 'apt' system for installation
  include_tasks: use-apt.yml
  when: ansible_pkg_mgr == "apt"

- name: delegate to 'apk' system for installation
  include_tasks: use-apk.yml
  when: ansible_pkg_mgr == "apk"

- name: delegate to 'yum' system for installation
  include_tasks: use-yum.yml
  when: ansible_pkg_mgr == "yum"

- name: delegate to 'homebrew' system for installation
  include_tasks: use-brew.yml
  when: ansible_pkg_mgr == "homebrew"

# inputrc
- name: use vi-mode in readline
  become: yes
  lineinfile:
    dest: '/etc/inputrc'
    line: 'set editing-mode vi'

# gitconfig
- name: setting vi-mode for git
  become: yes
  template:
    src: 'templates/gitconfig.j2'
    dest: '/etc/gitconfig'
    owner: root
    group: root
    mode: 0644
    backup: yes

# vim: ft=ansible :
