#!/usr/bin/env ansible-playbook
---

# Install Vim.
- name: install vim on debian base system
  become: yes
  zypper:
    name: vim
    state: present

- name: use vi-mode in bash
  become: yes
  lineinfile:
    dest: /etc/bash.bashrc
    line: 'set -o vi'

- name: setting $EDITOR
  become: yes
  lineinfile:
    dest: /etc/bash.bashrc
    line: 'export EDITOR=vim'

- name: use dark background in vim
  become: yes
  lineinfile:
    dest: /etc/vimrc
    line: 'set background=dark'

# vim: ft=yaml.ansible :
